#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Real mouse gestures in the shared UI. Fictional files, no native filesystem."""
import json, os, re
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'test-results';OUT.mkdir(exist_ok=True)
checks=[];errors=[]
def check(name,value=True):
    assert value,name
    checks.append(name);print('PASS',name,flush=True)
with sync_playwright() as pw:
    browser=pw.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),args=['--no-sandbox'])
    page=browser.new_page(viewport={'width':1320,'height':900});page.set_default_timeout(7000)
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.set_content((ROOT/'preview.html').read_text());page.wait_for_function('()=>OpenXplorer.state.ready&&OpenXplorer.state.tabs[0].loaded')
    page.evaluate("""()=>{window.calls=[];const orig=OpenXplorer.previewTransport.call.bind(OpenXplorer.previewTransport);OpenXplorer.previewTransport.call=async(m,a)=>{window.calls.push(m);return orig(m,a);};}""")
    def count():return page.locator('#tabs [role=tab]').count()
    def active():return page.evaluate('OpenXplorer.state.activeId')
    def uri():return page.evaluate('OpenXplorer.state.tabs.find(t=>t.id===OpenXplorer.state.activeId).uri')
    def row(name):return page.locator('.file-row,.file-tile').filter(has=page.locator('.name-text,.tile-name',has_text=re.compile('^'+re.escape(name)+'$')))
    def ready():page.wait_for_function('()=>{const s=OpenXplorer.state,t=s.tabs.find(t=>t.id===s.activeId);return t.loaded&&!t.busy}')
    def go(u):page.evaluate('(u)=>OpenXplorer.navigate(u)',u);ready()
    initial=active();home=uri()
    row('Documents').click(button='middle')
    check('Middle-click folder opens exactly one extra tab',count()==2)
    check('Background opening leaves the source active',active()==initial and uri()==home)
    check('New background tab has the actual folder URI',page.evaluate('OpenXplorer.state.tabs.at(-1).uri')==home+'/Documents')
    check('Background folders wait for activation before network/list requests',page.evaluate("calls.filter(m=>m==='list').length")==0)
    check('Source selection is not changed by middle-click',page.evaluate('OpenXplorer.state.selection.size')==0)
    check('No file-launch action is sent',page.evaluate("calls.includes('activateItem')")==False)
    page.locator('#tabs .tab').last.click();ready();check('Clicking the background tab loads its folder',uri()==home+'/Documents')
    n=count();row('Brand guidelines.pdf').click(button='middle')
    check('A PDF is not opened as a folder tab',count()==n and uri()==home+'/Documents')
    check('A middle-click file does not launch an external app',not page.evaluate("calls.includes('activateItem')"))
    go(home)
    row('Downloads').click(button='middle',modifiers=['Shift']);ready()
    check('Shift+middle-click opens in foreground',uri()==home+'/Downloads')
    check('Foreground middle-click adds only one tab',count()==n+1)
    page.locator('#tabs .tab.active').click(button='middle');ready();check('Middle-click still closes an existing tab once',count()==n)
    # Neither primary selection paste nor unsupported auxclick is needed.
    go(home);before=count();node=row('Pictures')
    node.dispatch_event('mousedown',{'button':1,'buttons':4});node.dispatch_event('mouseup',{'button':1,'buttons':0})
    check('Mouseup-only path supports older WebKit without auxclick',count()==before+1)
    node.dispatch_event('auxclick',{'button':1,'buttons':0});check('Later auxclick does not duplicate the new tab',count()==before+1)
    before=count();node.dispatch_event('mouseup',{'button':1,'buttons':0});check('A stray release without press does not open a tab',count()==before)
    node.dispatch_event('mousedown',{'button':1,'buttons':4});node.dispatch_event('mouseleave',{});node.dispatch_event('mouseup',{'button':1,'buttons':0})
    check('Leaving the folder before release cancels middle activation',count()==before)
    for name in ['Documents','Downloads']:
        before=count();id0=active();page.locator('#sidebar .side-entry').filter(has=page.locator('.name',has_text=re.compile('^'+name+'$'))).click(button='middle')
        check('Middle-click sidebar '+name+' opens in background',count()==before+1 and active()==id0)
    # Mounted volumes and paths are locations as well.
    before=count();page.locator('#sidebar .side-entry').filter(has=page.locator('.name',has_text='2 TB Volume')).click(button='middle')
    check('Mounted-volume sidebar entry supports middle-click',count()==before+1)
    page.evaluate("""()=>{OpenXplorer.state.env.mounts.push({label:'Sample Phone',uri:'mtp://[usb:001,010]/',mounted:true,kind:'device',canUnmount:true});OpenXplorer.renderSidebar();}""")
    phone=page.locator('#sidebar .side-entry').filter(has=page.locator('.name',has_text='Sample Phone'))
    check('MTP phone appears in the sidebar with a device icon',phone.count()==1 and phone.locator('[data-icon="phone"]').count()==1)
    check('Bracketed MTP URI has readable device breadcrumbs',page.evaluate("""()=>OpenXplorer.breadcrumbSegments('mtp://[usb:001,010]/Internal%20storage/DCIM').map(x=>x.label).join('|')""")=='Sample Phone|Internal storage|DCIM')
    check('Connected-device display does not expose a raw transport identifier',page.evaluate("""()=>OpenXplorer.displayUri('mtp://[usb:001,010]/Internal%20storage')""")=='Sample Phone / Internal storage')
    go(home+'/Documents');before=count();id0=active();page.locator('#breadcrumbs .crumb').filter(has_text=re.compile('^home$')).click(button='middle')
    check('Ancestor breadcrumb opens in background without navigating source',count()==before+1 and active()==id0 and uri()==home+'/Documents')
    go('pc:');before=count();page.locator('#landing .drive-card').filter(has=page.locator('.card-name',has_text='Local Disk')).click(button='middle')
    check('This PC drive cards support middle-click',count()==before+1)
    go('network:');page.wait_for_selector('.discovered-server');before=count();id0=active();page.locator('.discovered-server').first.click(button='middle')
    check('Network discovery cards open server tabs without leaving Network',count()==before+1 and active()==id0 and uri()=='network:')
    last=page.evaluate('OpenXplorer.state.tabs.at(-1).id');page.evaluate('(id)=>OpenXplorer.switchTab(id)',last);ready()
    names=page.evaluate('OpenXplorer.state.tabs.find(t=>t.id===OpenXplorer.state.activeId).entries.filter(e=>e.isDir).map(e=>e.name)')
    assert names,'sample share required';before=count();row(names[0]).click(button='middle')
    check('SMB mountable shares support middle-click',count()==before+1)
    entry=page.evaluate('(name)=>OpenXplorer.state.tabs.find(t=>t.id===OpenXplorer.state.activeId).entries.find(e=>e.name===name)',names[0])
    check('Share opens its target URI, not a fabricated local folder',page.evaluate('OpenXplorer.state.tabs.at(-1).uri')==(entry.get('targetUri') or entry['uri']))
    go(home);page.locator('#view').click();page.get_by_role('menuitem',name='Large icons',exact=True).click()
    before=count();row('Music').click(button='middle');check('Large-icon view supports middle-click',count()==before+1)
    page.locator('#status-list').click();go(home)
    page.evaluate("""()=>{const t=OpenXplorer.state.tabs.find(t=>t.id===OpenXplorer.state.activeId);t.entries.push({uri:t.uri+'/Archive.mp4',name:'Archive.mp4',isDir:true,type:'File folder',size:null,modified:0});t.dirty=true;OpenXplorer.applyTextSize(100);}""")
    before=count();row('Archive.mp4').click(button='middle');check('Real directory with file-looking extension remains a folder',count()==before+1)
    # Test the same helper through cached result rendering, with a distinct path.
    go(home);before=count()
    page.evaluate("""()=>{const s=OpenXplorer.state;s.query='example';document.getElementById('search').value='example';s.searchResults=[{uri:'smb://studio-nas/Projects/Example',targetUri:'smb://studio-nas/Projects/Example',parentUri:'smb://studio-nas/Projects',name:'Example',isDir:true,type:'File folder'}];s.filterCache=null;s.tabs.find(t=>t.id===s.activeId).dirty=true;OpenXplorer.applyTextSize(100);}""")
    row('Example').click(button='middle')
    check('Cached folder result opens its real SMB path in a new tab',count()==before+1 and page.evaluate('OpenXplorer.state.tabs.at(-1).uri')=='smb://studio-nas/Projects/Example')
    check('Middle-opening a search result does not erase the search',page.locator('#search').input_value()=='example')
    # A modest screenshot uses only fictional fixtures, not the user's images.
    page.evaluate("""()=>{const s=OpenXplorer.state;while(s.tabs.length>1)OpenXplorer.closeTab(s.tabs.at(-1).id);OpenXplorer.navigate('file:///home/demo');}""");ready()
    row('Documents').click(button='middle');row('Downloads').click(button='middle')
    page.screenshot(path=str(OUT/'middle-click-tabs.png'))
    check('No JavaScript errors in mouse interaction regression',not errors)
    browser.close()
(OUT/'ui-rc4.json').write_text(json.dumps({'scope':'Shared app HTML in Chromium, real mouse gestures plus mouseup-only compatibility events; simulated storage, not native WebKit','passed':len(checks),'checks':checks},indent=2))
