#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Modified 2026-09-06; original notices: licenses/Winspace-MIT.txt.
"""Real browser resize/click/key gestures; demo transport only, not native GTK."""
import json, os, re, sys, time
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'test-results';OUT.mkdir(exist_ok=True)

def main():
    checks=[];errors=[];requests=[];started=time.monotonic();status=1;report={}
    with sync_playwright() as p:
        browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),args=['--no-sandbox'])
        page=browser.new_page(viewport={'width':1480,'height':960});page.set_default_timeout(6500)
        page.on('pageerror',lambda e:errors.append(str(e)));page.on('request',lambda r:requests.append(r.url))
        page.evaluate("""()=>{const data={};window.__storage=data;Object.defineProperty(window,'localStorage',{value:{getItem:k=>data[k]??null,setItem:(k,v)=>data[k]=String(v),removeItem:k=>delete data[k]}})}""")
        def check(label,value=True):
            assert value,label;checks.append(label);print('PASS',label,flush=True)
        def ready(uri=None):
            page.wait_for_function("u=>{const s=OpenXplorer.state,t=s.tabs.find(t=>t.id===s.activeId);return s.ready&&t?.loaded&&!t.busy&&(!u||u===t.uri)}",arg=uri)
        def navigate(uri):page.evaluate('u=>{void OpenXplorer.navigate(u)}',uri);ready(uri)
        def row(name):return page.locator('.file-row').filter(has=page.locator('.name-text',has_text=re.compile('^'+re.escape(name)+'$')))
        def uri():return page.evaluate('OpenXplorer.state.tabs.find(t=>t.id===OpenXplorer.state.activeId).uri')
        def width(selector):return page.locator(selector).bounding_box()['width']
        def drag(selector,dx):
            box=page.locator(selector).bounding_box();x=box['x']+box['width']/2;y=box['y']+min(box['height']/2,18)
            page.mouse.move(x,y);page.mouse.down();page.mouse.move(x+dx,y,steps=15);page.mouse.up();page.wait_for_timeout(120)
        try:
            page.set_content((ROOT/'preview.html').read_text(),wait_until='load');ready('file:///home/demo')
            check('Release 1.0.0-rc.4 starts', '1.0.0-rc.4' in page.locator('#status-mode').inner_text())
            check('Quick-access counter and flag/heading removed',page.locator('.quick-heading,.quick-count').count()==0)
            check('Quick-access folders and drop target remain',page.locator('#quick-access .side-entry').count()>=6)
            old=width('.sidebar');drag('#sidebar-resizer',110)
            check('Sidebar drag changes its actual width',abs(width('.sidebar')-old-110)<2)
            check('Sidebar preference is saved',page.evaluate('OpenXplorer.state.env.preferences.sidebarWidth')==round(width('.sidebar')))
            page.locator('#sidebar-resizer').focus();page.keyboard.press('ArrowLeft')
            check('Sidebar handle supports keyboard resizing',abs(width('.sidebar')-old-100)<2)
            page.locator('#sidebar-resizer').dblclick();page.wait_for_timeout(100)
            check('Sidebar double-click restores default width',round(width('.sidebar'))==210)
            navigate('file:///home/demo/Documents')
            old=width('.column[data-field=name]');drag('.column[data-field=name] .column-resizer',90)
            check('Name column resizes with pointer',abs(width('.column[data-field=name]')-old-90)<2)
            check('Name width saves to preferences',page.evaluate('OpenXplorer.state.env.preferences.columnWidths.name')==round(width('.column[data-field=name]')))
            check('Resizing does not change sort',page.evaluate('OpenXplorer.state.sort')=='name')
            # Bring the remaining header handles into view via the synchronized scroller.
            for field in ['modified','type','size']:
                page.locator('#file-scroll').evaluate('(e)=>e.scrollLeft=4000');page.wait_for_timeout(60)
                oldw=width('.column[data-field='+field+']')
                drag('.column[data-field='+field+'] .column-resizer',25)
                check(field+' column resizes independently',abs(width('.column[data-field='+field+']')-oldw-25)<2)
            page.locator('#file-scroll').evaluate('(e)=>e.scrollLeft=150');page.wait_for_timeout(100)
            aligned=page.evaluate("""()=>{const h=[...document.querySelectorAll('.column')],r=[...document.querySelector('.file-row').children];return h.every((e,i)=>Math.abs(e.getBoundingClientRect().left-r[i].getBoundingClientRect().left)<1)}""")
            check('Headers and rows align during horizontal scrolling',aligned)
            check('Header scroll follows the file scroll',page.evaluate('Math.abs(document.getElementById("column-head").scrollLeft-document.getElementById("file-scroll").scrollLeft)<1'))
            page.locator('#file-scroll').evaluate('(e)=>e.scrollLeft=0');page.wait_for_timeout(50)
            page.locator('.column[data-field=name] .column-resizer').dblclick();page.wait_for_timeout(100)
            check('Double-click fits the Name column to loaded names',width('.column[data-field=name]')>=140)
            page.locator('.column[data-field=name] .column-resizer').focus();oldw=width('.column[data-field=name]');page.keyboard.press('ArrowRight')
            check('Column handle supports keyboard resizing',abs(width('.column[data-field=name]')-oldw-10)<2)
            # Preserve preferences through UI recreation with the same test storage.
            page.wait_for_timeout(150);saved=page.evaluate('OpenXplorer.state.env.preferences.columnWidths.name')
            saved_storage=page.evaluate('window.__storage');page.close()
            page=browser.new_page(viewport={'width':1480,'height':960});page.set_default_timeout(6500)
            page.on('pageerror',lambda e:errors.append(str(e)));page.on('request',lambda r:requests.append(r.url))
            page.evaluate("""data=>{window.__storage=data;Object.defineProperty(window,'localStorage',{value:{getItem:k=>data[k]??null,setItem:(k,v)=>data[k]=String(v),removeItem:k=>delete data[k]}})}""",saved_storage)
            page.set_content((ROOT/'preview.html').read_text(),wait_until='load');ready('file:///home/demo')
            check('Column width survives a preview restart',page.evaluate('OpenXplorer.state.env.preferences.columnWidths.name')==saved)
            # Individual breadcrumbs, including names requiring URI escaping.
            navigate('file:///home/demo/Documents/Client%20projects/Northwind')
            check('Every local ancestor has its own button',page.locator('#breadcrumbs .crumb').count()==6)
            check('No collapsed full-path button replaces breadcrumbs',page.locator('#breadcrumbs .location-text').count()==0)
            page.locator('#breadcrumbs .crumb').filter(has_text=re.compile('^Documents$')).click();ready('file:///home/demo/Documents')
            check('Clicking a local ancestor navigates directly')
            page.locator('#breadcrumbs .crumb').filter(has_text=re.compile('^demo$')).focus();page.keyboard.press('Enter');ready('file:///home/demo')
            check('Breadcrumb keyboard activation navigates rather than opening a selected file')
            segments=page.evaluate("OpenXplorer.breadcrumbSegments('smb://nas:1445/share/one/two/three/four/a%20b/%23snapshot')")
            check('Deep SMB path retains ALL ancestors',len(segments)==8)
            check('SMB hostname and nonstandard port are preserved',segments[0]['uri']=='smb://nas:1445/')
            check('SMB escaped names display decoded',segments[-1]['label']=='#snapshot' and segments[-2]['label']=='a b')
            check('SMB breadcrumb URI keeps literal # encoded',segments[-1]['uri'].endswith('/%23snapshot'))
            share='smb://archive-nas/Shared';navigate(share+'/Launch%20planning')
            check('SMB folder has separate server, share and folder buttons',page.locator('#breadcrumbs .crumb').count()==3)
            page.locator('#breadcrumbs .crumb').filter(has_text=re.compile('^Shared$')).click();ready(share)
            check('SMB ancestor click navigates without address editing')
            page.locator('#address-edit').click();check('Editable address still shows complete UNC path',page.locator('#address-input').input_value()==r'\\archive-nas\Shared');page.keyboard.press('Escape')
            check('Network tab shows green marker',page.locator('.tab.active .shared-bar').count()==1)
            page.evaluate('()=>OpenXplorer.addTab()');ready('file:///home/demo')
            check('Local tab has no network marker',page.locator('.tab.active .shared-bar').count()==0)
            check('Other network tab keeps its green marker',page.locator('.tab:not(.active) .shared-bar').count()==1)
            check('Mounted CIFS paths are recognized',page.evaluate("()=>{OpenXplorer.state.env.stableMounts=[{path:'/mnt/nas',fstype:'cifs'}];return OpenXplorer.networkLocation('file:///mnt/nas/folder')&&!OpenXplorer.networkLocation('file:///mnt/nas-other/folder')}"))
            # Defensive UI dedup mirrors native AppInfo dedup (native tests cover real helper logic).
            navigate('file:///home/demo/Documents')
            page.evaluate("()=>OpenXplorer.state.env.editors=[{id:'code.desktop',name:'Visual Studio Code'},{id:'com.visualstudio.code.desktop',name:'Visual Studio Code'},{id:'codium.desktop',name:'VSCodium'}]")
            row('Work').click(button='right')
            check('Visual Studio Code shortcut is not duplicated',page.get_by_role('menuitem',name='Open in Visual Studio Code',exact=True).count()==1)
            check('Distinct VSCodium shortcut remains',page.get_by_role('menuitem',name='Open in VSCodium',exact=True).count()==1)
            page.keyboard.press('Escape');row('Work').click();page.keyboard.type('cl',delay=35)
            check('Type-to-select selects matching row',page.locator('.file-row.selected .name-text').inner_text()=='Client projects')
            check('No blue outline on the whole file pane',page.locator('#main').evaluate("e=>getComputedStyle(e).outlineStyle==='none'"))
            check('Keyboard focus remains visible on the selected item',page.locator('.file-row.selected').evaluate("e=>getComputedStyle(e).outlineStyle==='solid'"))
            # Size calculation from real preview tree, no invented physical/ZFS bytes.
            row('Client projects').click(button='right');page.get_by_role('menuitem',name='Calculate folder size',exact=True).click()
            page.wait_for_function('()=>!OpenXplorer.state.sizeRun&&OpenXplorer.state.folderSizes.size>0')
            check('Folder size appears in Size column',bool(row('Client projects').locator('.size-cell').inner_text()))
            result=page.evaluate("OpenXplorer.state.folderSizes.get('file:///home/demo/Documents/Client%20projects')")
            check('Sample folder scan totals its actual fixture metadata',result['bytes']==68542 and result['status']=='complete')
            check('Size completion distinguishes logical bytes', 'Logical bytes' in page.locator('#size-scan-label').inner_text())
            page.locator('#size-scan-stop').click();expect(page.locator('#size-scan')).to_be_hidden()
            row('Client projects').click();page.keyboard.press('Alt+Enter');expect(page.locator('#prop-general')).to_contain_text('66.9 KB')
            check('Properties uses the same measured folder total')
            check('Properties exposes explicit recalculation',page.locator('#modal').get_by_role('button',name='Calculate folder size',exact=True).count()==1)
            page.keyboard.press('Escape')
            # Properties remains attached to its originating tab while snapshot tabs open.
            navigate(share);origin=page.evaluate('OpenXplorer.state.activeId')
            row('Launch planning').click(button='right');page.get_by_role('menuitem',name='Previous versions',exact=True).click()
            expect(page.locator('#modal .version-row')).to_have_count(3)
            page.evaluate("()=>{window.__versionList=document.querySelector('#modal .versions-list');window.__versionList.dataset.preserved='yes';}")
            page.locator('#modal .version-row').first.get_by_role('button',name='Browse',exact=True).click();ready()
            check('Browse opens a new snapshot tab',page.evaluate('OpenXplorer.state.activeId')!=origin and page.evaluate('OpenXplorer.readonlyLocation(OpenXplorer.state.tabs.find(t=>t.id===OpenXplorer.state.activeId).uri)'))
            check('Origin dialog is not overlaid on the snapshot tab',page.locator('#modal-layer').is_hidden())
            check('Origin owns a preserved dialog',page.evaluate('id=>!!OpenXplorer.state.tabs.find(t=>t.id===id).savedDialog',origin))
            check('Snapshot network tab also has green marker',page.locator('.tab.active .shared-bar').count()==1)
            page.locator('.tab[data-tab-id='+origin+']').click();expect(page.locator('#modal-layer')).to_be_visible()
            check('Returning restores the SAME versions list without another lookup',page.evaluate("document.querySelector('#modal .versions-list')===window.__versionList"))
            check('Previous versions tab remains selected',page.locator('#modal #prop-tab-versions').get_attribute('aria-selected')=='true')
            # Tabstrip stays outside scoped backdrop, so it can be clicked while the dialog is open.
            page.locator('#modal .version-row').nth(1).get_by_role('button',name='Browse',exact=True).click();ready()
            check('Another snapshot can be opened without losing the original dialog',page.evaluate('id=>!!OpenXplorer.state.tabs.find(t=>t.id===id).savedDialog',origin))
            page.locator('.tab[data-tab-id='+origin+']').click();expect(page.locator('#modal .versions-list')).to_be_visible()
            page.screenshot(path=str(OUT/'previous-versions-tabs.png'))
            page.keyboard.press('Control+Tab');expect(page.locator('#modal-layer')).to_be_hidden()
            page.locator('.tab[data-tab-id='+origin+']').click();expect(page.locator('#modal-layer')).to_be_visible()
            check('Ctrl+Tab suspends Properties rather than closing it')
            # Open settings with property dialog active: settings remains a full page.
            page.keyboard.press('Control+,');ready('settings:')
            check('Settings opens as a dedicated tab/page',page.locator('#landing.settings-page').is_visible() and page.locator('.tab.active').inner_text().strip()=='Settings')
            check('Settings is not a modal',page.locator('#modal-layer').is_hidden())
            check('Properties survives opening Settings',page.evaluate('id=>!!OpenXplorer.state.tabs.find(t=>t.id===id).savedDialog',origin))
            check('Settings has section navigation',page.locator('.settings-nav-link').count()==5)
            check('Full-page settings includes drives and cache controls',page.get_by_role('checkbox',name='Cache Local Disk',exact=True).count()==1 and page.get_by_role('checkbox',name='Cache 2 TB Volume',exact=True).count()==1)
            check('Pseudo Settings URI is not an index candidate',page.get_by_role('checkbox',name='Cache Settings',exact=True).count()==0)
            page.get_by_role('combobox',name='Theme',exact=True).select_option('light')
            check('Settings changes theme without closing the page',page.locator('html').get_attribute('data-theme')=='light' and uri()=='settings:')
            page.get_by_role('combobox',name='Theme',exact=True).select_option('dark')
            page.locator('#context-menu-style').select_option('win10')
            page.get_by_role('button',name='Reset sidebar and column widths',exact=True).click()
            check('Layout can be reset from Settings',page.evaluate('OpenXplorer.state.env.preferences.sidebarWidth===210&&Object.keys(OpenXplorer.state.env.preferences.columnWidths).length===0'))
            page.locator('.settings-body').evaluate('(e)=>e.scrollTop=0');page.wait_for_timeout(450)
            page.screenshot(path=str(OUT/'settings-page.png'))
            settingsid=page.evaluate('OpenXplorer.state.activeId');page.keyboard.press('Control+,');ready('settings:')
            check('Opening Settings again reuses its existing tab',page.evaluate('OpenXplorer.state.tabs.filter(t=>t.uri==="settings:").length')==1)
            page.locator('.tab[data-tab-id='+origin+']').click();expect(page.locator('#modal-layer')).to_be_visible();page.keyboard.press('Escape')
            check('Explicit Close/Escape still dismisses Properties',page.locator('#modal-layer').is_hidden())
            # Search path column gets its own resizable field.
            navigate(share);page.locator('#search').fill('Design');page.wait_for_function('()=>OpenXplorer.state.query==="Design"&&!OpenXplorer.state.searchBusy')
            check('Cached search uses a Folder path resize handle',page.locator('.column[data-field=parentUri] .column-resizer').count()==1)
            page.locator('#file-scroll').evaluate('(e)=>e.scrollLeft=450');page.wait_for_timeout(50)
            oldw=width('.column[data-field=parentUri]');drag('.column[data-field=parentUri] .column-resizer',40)
            check('Search Folder path column resizes independently',abs(width('.column[data-field=parentUri]')-oldw-40)<2)
            navigate(share);page.evaluate('()=>OpenXplorer.resetLayout()');drag('#sidebar-resizer',72)
            page.locator('#details-toggle').click();page.wait_for_timeout(100)
            page.mouse.move(500,60);page.screenshot(path=str(OUT/'workspace-layout.png'))
            check('No JavaScript exceptions',not errors);check('Offline preview performs no external requests',not requests)
            status=0
        except Exception as e:
            import traceback;traceback.print_exc();report['failure']=str(e);page.screenshot(path=str(OUT/'v06-failure.png'))
        finally:
            report.update(success=status==0,count=len(checks),checks=checks,errors=errors,requests=requests,elapsedSeconds=round(time.monotonic()-started,2),scope='Chromium actual UI and pointer/keyboard gestures; simulated filesystem/SMB transport')
            (OUT/'ui-v06.json').write_text(json.dumps(report,indent=2)+'\n');browser.close()
    return status
if __name__=='__main__':raise SystemExit(main())
