#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""0.9 regression: actual app HTML with simulated storage, not native WebKit."""
from pathlib import Path
import json,os
from playwright.sync_api import sync_playwright,expect
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'test-results';OUT.mkdir(exist_ok=True)
checks=[];errors=[]
def check(name,ok=True):
 assert ok,name
 checks.append(name)
 print('PASS',name,flush=True)
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),args=['--no-sandbox'])
 page=b.new_page(viewport={'width':1440,'height':900});page.set_default_timeout(9000);page.on('pageerror',lambda e:errors.append(str(e)))
 page.evaluate("()=>{const d={};Object.defineProperty(window,'localStorage',{value:{getItem:k=>d[k]??null,setItem:(k,v)=>d[k]=String(v),removeItem:k=>delete d[k]}})}")
 page.set_content((ROOT/'preview.html').read_text(),wait_until='load')
 page.wait_for_function('()=>window.OpenXplorer?.state.ready && window.OpenXplorerTour')
 page.wait_for_function('()=>OpenXplorer.state.tabs[0].loaded')
 entry={'uri':'smb://archive-nas/Shared/Launch%20planning','name':'Launch planning','isDir':True}
 page.evaluate('(e)=>{void OpenXplorer.propertiesDialog(e,"versions")}',entry)
 expect(page.locator('.version-row')).to_have_count(3)
 check('All snapshot fixtures have a right-side date',page.locator('.version-date time').count()==3)
 check('Date is readable, not only raw snapshot label','Sep 5, 2026' in page.locator('.version-date').first.inner_text())
 check('Time displayed separately','18:00:00' in page.locator('.version-time').first.inner_text())
 check('Date source is visible once for the list','Dates are read from snapshot names' in page.locator('.version-date-note').inner_text())
 check('Date has machine-readable ISO attribute',page.locator('.version-date time').first.get_attribute('datetime')=='2026-09-05T18:00:00')
 check('Timezone uncertainty disclosed','not supplied' in page.locator('.version-date').first.get_attribute('title'))
 text=page.locator('.version-text').first.bounding_box();date=page.locator('.version-date').first.bounding_box()
 check('Date column lies to the right of the snapshot label',date['x']>=text['x']+text['width']-1)
 original=page.evaluate('OpenXplorer.state.activeId')
 page.locator('.version-actions button').filter(has_text='Browse').first.click()
 page.wait_for_function('()=>OpenXplorer.state.tabs.find(t=>t.id===OpenXplorer.state.activeId).loaded')
 check('Snapshot opened in separate tab',page.locator('.tab').count()==2)
 check('Original dialog is suspended',not page.locator('#modal-layer').is_visible())
 expect(page.locator('.snapshot-tab-badge')).to_have_count(1)
 check('Previous version badge is explicit',page.locator('.snapshot-tab-badge').inner_text()=='Previous version')
 check('Historical tab retains network green marker',page.locator('.snapshot-tab .shared-bar').count()==1)
 check('Accessible tab description says Previous version','Previous version' in page.locator('.snapshot-tab').get_attribute('aria-label'))
 check('Historical banner is visible',page.locator('#snapshot-banner').is_visible())
 check('Banner identifies read-only treatment','Read-only in OpenXplorer' in page.locator('#snapshot-banner').inner_text())
 check('New file/folder remains disabled in history',page.locator('#new').is_disabled())
 page.locator('.file-row').filter(has=page.locator('.name-text',has_text='Receipts')).dblclick()
 page.wait_for_function('()=>OpenXplorer.state.tabs.find(t=>t.id===OpenXplorer.state.activeId).uri.endsWith("/Receipts")')
 check('Badge persists inside a historical subfolder',page.locator('.snapshot-tab-badge').count()==1)
 page.evaluate('(id)=>OpenXplorer.switchTab(id)',original)
 expect(page.locator('#modal-layer')).to_be_visible()
 check('Original version chooser preserved',page.locator('.version-row').count()==3)
 check('Original chooser keeps date labels',page.locator('.version-date').first.is_visible())
 check('Live tab does not show historical banner',not page.locator('#snapshot-banner').is_visible())
 page.keyboard.press('Escape');page.evaluate('()=>OpenXplorer.closeModal()')
 page.evaluate('()=>OpenXplorer.navigate("file:///home/demo")')
 check('Date unavailable never uses a modified-time fallback',page.evaluate('()=>OpenXplorerSnapshots.describe({label:"manual",snapshotModified:123}).date')=='Date unavailable')
 page.evaluate('()=>OpenXplorerTour.play()')
 page.wait_for_function('()=>["complete","error"].includes(document.documentElement.dataset.tourPhase)',timeout=20000)
 check('Tour completes through actual pointer handlers',page.locator('html').get_attribute('data-tour-phase')=='complete')
 check('Tour added Design pin',page.evaluate('()=>OpenXplorer.state.env.quick.some(p=>p.uri==="smb://studio-nas/Projects/Design")'))
 check('Tour opened the new pin',page.evaluate('()=>OpenXplorer.state.tabs.find(t=>t.id===OpenXplorer.state.activeId).uri')=='smb://studio-nas/Projects/Design')
 page.evaluate('()=>{void OpenXplorerTour.reset()}');page.wait_for_function('()=>document.documentElement.dataset.tourPhase==="ready"')
 check('Reset removes only tour pin',not page.evaluate('()=>OpenXplorer.state.env.quick.some(p=>p.uri==="smb://studio-nas/Projects/Design")'))
 page.evaluate('()=>{void OpenXplorerTour.play()}');page.wait_for_function('()=>document.documentElement.dataset.tourPhase==="playing"');page.evaluate('()=>OpenXplorerTour.stop()');page.wait_for_timeout(500)
 check('Stop cancels the current walkthrough',page.locator('html').get_attribute('data-tour-phase')=='stopped')
 check('Stop removes cursor and cancels drag',page.locator('.demo-cursor').count()==0 and page.evaluate('()=>!OpenXplorer.state.drag'))
 check('No page JavaScript errors',not errors)
 b.close()
(OUT/'ui-v09.json').write_text(json.dumps({'passed':True,'checks':len(checks),'details':checks,'errors':errors,'scope':'Chromium actual application HTML, fictional files, simulated storage; no native GTK/WebKit or SMB'},indent=2)+'\n')
print('Passed',len(checks),'checks')
