// SPDX-License-Identifier: AGPL-3.0-only
import {site,type Vibe} from '../lib/site';
import docs from '../lib/docs.json';
import {Folder,Icon} from './icons';
import {Screenshot,ProductDemo,BentoFeatures} from './product';
export type Doc=typeof docs[number];
export function Brand(){return <a className="brand" href="/" aria-label="OpenXplorer home"><Folder/><span>Open<span className="word-x">X</span>plorer</span></a>;}
export function Header({vibe='vercel',active='',docSlug=''}:{vibe?:Vibe;active?:string;docSlug?:string}){
 return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><div className="header-inner"><Brand/><nav className="desktop-nav" aria-label="Primary navigation"><a href="/#features" className={active==='features'?'active':''}>Features</a><a href="/docs/introduction/" className={active==='docs'?'active':''} aria-current={active==='docs'?'page':undefined}>Documentation</a><a href="/source/" className={active==='source'?'active':''} aria-current={active==='source'?'page':undefined}>Open source</a></nav><div className="header-actions"><button className="search-trigger" data-search-open="" aria-label="Search documentation"><Icon name="search" size={15}/><span>Search docs</span></button><a className="header-download" href={site.releases}>Releases <Icon name="code" size={14}/></a><button className="mobile-menu-button" data-menu-toggle="" aria-expanded="false" aria-label={active==='docs'?'Open documentation menu':'Open menu'} aria-controls="mobile-navigation"><Icon name="menu"/></button></div></div><nav id="mobile-navigation" className="mobile-nav" data-mobile-nav="" aria-label={active==='docs'?'Documentation menu':'Main menu'} hidden>
 <div className="mobile-nav-primary"><a href="/#features">Features</a><a href="/docs/introduction/">Documentation</a><a href="/source/">Source code</a><a href={site.releases}>Releases</a></div>
 {active==='docs'&&<div className="mobile-doc-topics">{['Get started','Using OpenXplorer','Build & contribute','Project'].map(group=><div className="mobile-doc-group" key={group}><strong>{group}</strong>{docs.filter(d=>d.group===group).map(d=><a key={d.slug} href={'/docs/'+d.slug+'/'} aria-current={d.slug===docSlug?'page':undefined}>{d.title}{d.slug===docSlug&&<Icon name="check" size={16}/>}</a>)}</div>)}</div>}
 </nav></header></>;
}
export function Footer(){return <footer className="site-footer"><div className="footer-main"><div><Brand/><p>Familiar by design. Open by choice.</p></div><div className="footer-links"><a href="/docs/installation/">Installation</a><a href="/docs/license/">AGPL-3.0</a><a href={site.repository}>GitHub repository <Icon name="code" size={14}/></a></div></div><div className="footer-fine"><span>© 2026 OpenXplorer contributors. No warranty.</span><span>Independent. Not affiliated with Microsoft, Zorin or Vercel.</span></div></footer>;}
export function GlobalSearch(){return <><dialog className="search-dialog" id="docs-search" aria-label="Search documentation"><div className="search-dialog-top"><Icon name="search"/><input autoComplete="off" id="docs-search-input" aria-label="Search topics" placeholder="Search documentation…"/><button data-search-close="" aria-label="Close search"><kbd>Esc</kbd></button></div><div className="search-results" id="docs-search-results" aria-live="polite"/><footer>Search stays in your browser.　↵ Open result</footer></dialog><div className="toast" id="site-toast" role="status" aria-live="polite"/></>;}
export function DesignBar({vibe}:{vibe:Vibe}){return <div className="design-bar"><span><span className="micro-label">DESIGN LAB</span> Three directions. One open project.</span><nav aria-label="Design directions">{([['windows','01','Fluent'],['zorin','02','Horizon'],['vercel','03','Blueprint']] as const).map(([key,no,label])=><a key={key} href={'/concepts/'+key+'/'} aria-current={vibe===key?'page':undefined}><span>{no}</span> {label}</a>)}</nav></div>;}
function CodeBlock({code,label='Terminal'}:{code:string;label?:string}){return <div className="code-block"><div className="code-heading"><span><Icon name="terminal" size={13}/> {label}</span><button data-copy-code="" aria-label="Copy command"><Icon name="copy" size={14}/><span>Copy</span></button></div><pre><code>{code}</code></pre></div>;}
const features=[
 ['network','Network, without the detour.','Your NAS, local folders and saved shares in one place. Real paths, clickable breadcrumbs, and a place for every pin.','SMB / GVfs','network-shares'],
 ['search','Find it. Keep your bearings.','Opt in to a local filename index. Search names and paths, then open the actual location—not another search maze.','SQLite index','search-indexing'],
 ['grid','A workspace that fits you.','Tabs, resizable columns, light and dark modes, and the classic context menu. Familiar details, with room to make it yours.','Your preferences','interface'],
];
function FeatureGrid(){return <section id="features" className="section features-section"><div className="section-heading"><div><span className="eyebrow">Familiar details</span><h2>Less looking around.<br/>More getting things done.</h2></div><p>A file manager should feel like home.<br/>Even when home is on your NAS.</p></div><div className="feature-grid">{features.map(([icon,title,text,tag,slug],i)=><a className="feature-card" href={'/docs/'+slug+'/'} key={slug}><div className="feature-card-top"><Icon name={icon} size={24}/><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p><div className="feature-bottom"><code>{tag}</code><Icon name="arrow" size={18}/></div></a>)}</div></section>;}
function GuidePreview(){return <section id="guide" className="section guide-section"><div className="section-heading"><div><span className="eyebrow">Documentation</span><h2>A clear path from here.</h2></div><a className="text-link" href="/docs/introduction/">Explore the docs <Icon name="arrow" size={17}/></a></div><div className="guide-window"><aside><span className="micro-label">Get started</span><a href="/docs/introduction/">Introduction</a><a className="selected" href="/docs/installation/"><Icon name="download" size={14}/> Installation</a><span className="micro-label">Your workflow</span><a href="/docs/network-shares/">SMB & network shares</a><a href="/docs/search-indexing/">Search & indexing</a><a href="/docs/desktop-integration/">Default file manager</a></aside><article><span className="crumb-small">Documentation <Icon name="chevron" size={10}/> Installation</span><h3 id="guide-install">At home on Linux.</h3><p>Zorin-first. Built on native Linux storage tools. Install a development build without changing your desktop.</p><CodeBlock code={'sudo apt install ./openxplorer_1.0.0~rc4_all.deb\nopenxplorer'}/><div className="small-note"><Icon name="info" size={15}/><span>Test with a disposable folder first. Native desktop and NAS validation is still in progress.</span></div></article><nav aria-label="Guide preview contents"><span>On this page</span><a href="#guide-install">Install the package</a><a href="/docs/installation/#upgrade">Upgrade from Winspace</a><a href="/docs/installation/#first-run">First-run checklist</a></nav></div></section>;}
function OpenSection(){return <section id="open-source" className="section open-section"><div className="open-emblem"><Icon name="code" size={42}/><span>AGPL<br/>3.0</span></div><div><span className="eyebrow">Open by choice</span><h2>Yours to use.<br/>Yours to understand.</h2><p>Read the code. Change the details. Share what you build.<br/>The desktop app, website, documentation and build tools are all here.</p><a className="button secondary" href={site.repository}><Icon name="code" size={17}/> Browse the GitHub repository <Icon name="arrow" size={16}/></a></div><div className="source-tree"><div><i/> openxplorer/</div><p>├── desktop/ <span>the application</span></p><p>├── apps/web/ <span>this website</span></p><p>├── docs/ <span>the knowledge</span></p><p>└── LICENSE <span>AGPL-3.0-only</span></p><a href="/source/">Nothing behind a login <Icon name="arrow" size={15}/></a></div></section>;}
function DownloadSection(){return <section id="download" className="section download-section"><div><span className="eyebrow">Development release {site.version}</span><h2>Get OpenXplorer.</h2><p>For Zorin OS and compatible Ubuntu or Debian systems.<br/>Packages and release notes live on GitHub Releases.</p></div><div className="download-side"><a className="button primary" href={site.releases}><Icon name="code" size={18}/> View releases on GitHub</a><small>v{site.version} · AGPL-3.0-only · no website-hosted downloads</small><a className="subtle-link" href="/docs/installation/">Read installation & compatibility notes →</a></div></section>;}
export function Home({vibe='zorin',lab=false}:{vibe?:Vibe;lab?:boolean}){
 const copy={zorin:{title:<>A familiar place.<br/>A fresh start.</>,desc:'Windows File Explorer-inspired, built for Linux. Your local files, NAS shares and favorite folders, right where you expect them.'},windows:{title:<>Your files.<br/>Right at home.</>,desc:'Familiar controls. Native Linux storage. A clear home for your folders, files and network shares.'},vercel:{title:<>Familiar files.<br/>Open possibilities.</>,desc:'Local files and SMB shares in one open workspace. Built for Zorin, with compatible Ubuntu and Debian systems in mind.'}}[vibe];
 return <div className={'site theme-'+vibe+' product-home'} data-vibe={vibe}><Header vibe={vibe}/>{lab&&<DesignBar vibe={vibe}/>}<main id="main">
 <section className="product-hero"><div className="product-hero-copy"><p className="hero-intro">Made for your next chapter</p><h1>{copy.title}</h1><p>{copy.desc}</p><div className="hero-actions"><a className="button primary" href={site.releases} aria-describedby="release-status"><Icon name="code" size={18}/> View releases</a><a className="button secondary desktop-demo-link" href="#demo">Try it in your browser</a><a className="button secondary mobile-feature-link" href="#features">Explore features</a></div><p className="hero-footnote" id="release-status">Development release {site.version} · AGPL-3.0-only.<br/>For Zorin OS and compatible Ubuntu or Debian systems.<br/><a href="/docs/installation/">Installation &amp; compatibility</a> · <a href={site.repository}>Source repository</a></p></div><a href="#features" className="product-hero-image" aria-label="Explore OpenXplorer features"><Screenshot name="explorer-light" alt="Actual OpenXplorer interface in light mode showing Projects on a sample NAS" priority/><span className="product-image-note">The actual interface. Entirely fictional sample files.</span></a></section>
 <section id="demo" className="section product-demo-section desktop-demo-only"><div className="section-heading"><h2>Take the familiar route.</h2><p>Type a path. Open the NAS. Pin a folder.<br/>Try the interface before installing anything.</p></div><ProductDemo/></section>
 <BentoFeatures/><GuidePreview/><OpenSection/><DownloadSection/></main><Footer/><GlobalSearch/></div>;
}
export function DocsSidebar({current}:{current:string}){return <aside className="docs-sidebar"><div className="docs-label"><Icon name="book" size={15}/><span>Documentation</span><code>{site.version}</code></div><button className="docs-sidebar-search" data-search-open=""><Icon name="search" size={14}/> Search docs </button><nav aria-label="Documentation topics">{['Get started','Using OpenXplorer','Build & contribute','Project'].map(group=><div key={group} className="docs-nav-group"><span>{group}</span>{docs.filter(d=>d.group===group).map(d=><a href={'/docs/'+d.slug+'/'} className={d.slug===current?'selected':''} aria-current={d.slug===current?'page':undefined} key={d.slug}>{d.title}</a>)}</div>)}</nav><a className="docs-source-link" href={site.repository}><Icon name="code" size={15}/> Browse on GitHub <Icon name="arrow" size={13}/></a></aside>;}
export function DocPage({slug='introduction'}:{slug?:string}){
 const index=docs.findIndex(d=>d.slug===slug),doc=docs[index]||docs[0],prev=docs[index-1],next=docs[index+1];
 return <div className="site theme-zorin docs-site"><Header active="docs" docSlug={doc.slug}/><div className="docs-layout"><DocsSidebar current={doc.slug}/><main id="main" className="doc-article"><div className="doc-meta"><span>{doc.group}<Icon name="chevron" size={12}/>{doc.title}</span><button data-copy-markdown={doc.slug} aria-label="Copy page as Markdown"><Icon name="copy" size={13}/> Copy page as Markdown</button></div><header><h1>{doc.title}</h1><p>{doc.description}</p></header>{doc.sections.map(s=><section id={s.id} key={s.id} data-doc-section=""><h2><a href={'#'+s.id}>{s.title}<span>#</span></a></h2>{s.paragraphs.map((p,i)=><p key={i}>{p}</p>)}{'items' in s&&s.items?.length&&<ul>{s.items.map((t:string)=><li key={t}>{t}</li>)}</ul>}{'code' in s&&s.code&&<CodeBlock code={s.code}/>} {'image' in s&&s.image&&<Screenshot name={String(s.image)} alt={s.imageAlt||s.title} caption="Actual HTML interface. Sample files; no live NAS connection."/>} {'demo' in s&&s.demo&&<ProductDemo compact/>} {'callout' in s&&s.callout&&<div className="doc-callout"><Icon name="info" size={18}/><p>{s.callout}</p></div>}</section>)}<div className="doc-bottom-note">Project documentation · OpenXplorer {site.version} · <a href="/docs/license/">AGPL-3.0-only</a></div><div className="doc-pagination">{prev?<a href={'/docs/'+prev.slug+'/'}><small>Previous</small><span><Icon name="back" size={16}/>{prev.title}</span></a>:<span/>}{next&&<a href={'/docs/'+next.slug+'/'}><small>Next</small><span>{next.title}<Icon name="arrow" size={16}/></span></a>}</div></main><aside className="docs-toc"><span>On this page</span><nav aria-label="On this page">{doc.sections.map(s=><a key={s.id} href={'#'+s.id}>{s.title}</a>)}</nav><div className="toc-note"><Icon name="branch" size={17}/><strong>Built in the open.</strong><p>Read, improve and share the project.</p><a href={site.repository}>Get the source <Icon name="arrow" size={13}/></a></div></aside></div><Footer/><GlobalSearch/></div>;
}
export function Concepts(){return <div className="site theme-vercel"><Header/><main id="main" className="concepts-page section"><span className="eyebrow">OPENXPLORER / DESIGN LAB</span><h1>Three ways to feel at home.</h1><p>The same open-source project. Three distinctly different expressions.</p><div className="concept-grid">{([['windows','01','Fluent','Familiar, soft and precise.','Win 11-inspired frosted surfaces, blue highlights and a centered, product-first layout.'],['zorin','02','Horizon','A lighter place to land.','The selected direction: Zorin blues, real application views and an interactive workspace.'],['vercel','03','Blueprint','Built for the open.','Developer-style precision, dark grids and Zorin blue.']] as const).map(([v,no,title,tag,description])=><a className={'concept-card concept-'+v} href={'/concepts/'+v+'/'} key={v}><div className="concept-thumbnail"><span>OpenXplorer</span><strong>{tag}</strong><div className="mini-window"><i/><i/><i/></div></div><div className="concept-description"><code>{no} / {v==='vercel'?'VERCEL × ZORIN':v==='windows'?'WINDOWS 11':'ZORIN OS'}</code><h2>{title}<Icon name="arrow"/></h2><p>{description}</p><span>Explore this direction →</span></div></a>)}</div><a className="text-link" href="/docs/introduction/">All directions share the three-column documentation system <Icon name="arrow" size={16}/></a></main><Footer/><GlobalSearch/></div>;}
export function SourcePage(){return <div className="site theme-vercel"><Header active="source"/><main id="main" className="source-page section"><span className="eyebrow">OPEN BY CHOICE</span><h1>Not just a product.<br/><span>The whole project.</span></h1><p>The application, the website, the docs and the tools to build them.<br/>Publicly available under AGPL-3.0-only.</p><div className="source-downloads"><a href={site.repository} className="source-download"><Icon name="code" size={28}/><div><h2>Browse the GitHub repository</h2><p>OpenXplorer {site.version} · editable project + build tools</p></div><Icon name="arrow"/></a></div><div className="source-info-grid"><section><h2>What you can do</h2><p>Use the application, study how it works, and modify and redistribute it under the license terms. The full license is included, along with preserved third-party notices.</p><a href="/LICENSE.txt">Read the full AGPL-3.0 license →</a></section><section><h2>What you should know</h2><p>This is an independent development project. No warranty is provided. If you distribute or host a modified version, review the corresponding-source obligations in the actual license.</p><a href="/docs/license/">License & source documentation →</a></section></div><div className="doc-callout"><Icon name="info"/><p>The public repository is the preferred corresponding source for the desktop application and this website, including build tools and third-party license notices.</p></div></main><Footer/><GlobalSearch/></div>;}
